require('plugin-config.lualine')
require('plugin-config.nvim-tree')
require('plugin-config.telescope')
require('plugin-config.treesitter')
require('plugin-config.lsp_config')
require('plugin-config.bufferline')
require('plugin-config.toggleterm')
require('plugin-config.completions')
